@url=http://localhost:8080/course


GET {{url}}/1 HTTP/1.1
x-key:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWGFzYW5ib3kiLCJsYXN0bmFtZSI6IkFiZHVyYXN1bG92IiwicGhvbmVOdW1iZXIiOiIrOTE5OTI4NDczIiwiaWF0IjoxNjc4OTc4MDU3fQ.nXOykdZs5Gk7cOBNkwaNeE5O4O1x5IFxNtbK5WklQYQ

###
GET {{url}}/all/
x-key:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWGFzYW5ib3kiLCJsYXN0bmFtZSI6IkFiZHVyYXN1bG92IiwicGhvbmVOdW1iZXIiOiIrOTE5OTI4NDczIiwiaWF0IjoxNjc4OTc4MDU3fQ.nXOykdZs5Gk7cOBNkwaNeE5O4O1x5IFxNtbK5WklQYQ\

###
POST {{url}}
x-key:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiWGFzYW5ib3kiLCJsYXN0bmFtZSI6IkFiZHVyYXN1bG92IiwicGhvbmVOdW1iZXIiOiIrOTE5OTI4NDczIiwiaWF0IjoxNjc4OTc4MDU3fQ.nXOykdZs5Gk7cOBNkwaNeE5O4O1x5IFxNtbK5WklQYQ
id:1